In [25]:
import pandas as pd

## panda series

In [27]:
grades = pd.Series([88, 90, 80, 97, 99])
grades

0    88
1    90
2    80
3    97
4    99
dtype: int64

In [28]:
print(grades.mean())

90.8

In [29]:
print(grades.min())
print(grades.max())

80
99

## panda dataframe

In [31]:
# one way to create a dictionary

data = {
    "Name": ["Alice", "Bob", "Charlie"],
    "Age": [25, 30, 35],
    "City": ["SF", "LA", "NY"]
}

data

{'Name': ['Alice', 'Bob', 'Charlie'],
 'Age': [25, 30, 35],
 'City': ['SF', 'LA', 'NY']}

In [32]:
print(data.keys())

dict_keys(['Name', 'Age', 'City'])

In [33]:
print(data.values())

dict_values([['Alice', 'Bob', 'Charlie'], [25, 30, 35], ['SF', 'LA', 'NY']])

In [34]:
print(data["City"])

['SF', 'LA', 'NY']

In [35]:
df = pd.DataFrame(data)
df

      Name  Age City
0    Alice   25   SF
1      Bob   30   LA
2  Charlie   35   NY

In [36]:
df["Name"]

0      Alice
1        Bob
2    Charlie
Name: Name, dtype: str

In [37]:
df[["Name", "Age"]]

      Name  Age
0    Alice   25
1      Bob   30
2  Charlie   35

In [38]:
df[df["Age"] > 25]

      Name  Age City
1      Bob   30   LA
2  Charlie   35   NY

In [39]:
df[df["City"] == "SF"]

    Name  Age City
0  Alice   25   SF

In [40]:
df["Age"] = df["Age"] + 1
df

      Name  Age City
0    Alice   26   SF
1      Bob   31   LA
2  Charlie   36   NY

In [41]:
# will keep adding 1 if cell is run over and over, remembers df

In [42]:
# df["Age"] = pd.Series([1, 2, 3])
# df

# changes the ages

In [43]:
df["Senior"] = df["Age"] > 30 
df

      Name  Age City  Senior
0    Alice   26   SF   False
1      Bob   31   LA    True
2  Charlie   36   NY    True

In [44]:
df.loc[0, :]

# df.loc[row, column]

Name      Alice
Age          26
City         SF
Senior    False
Name: 0, dtype: object

In [45]:
df.loc[:, "Name"]

0      Alice
1        Bob
2    Charlie
Name: Name, dtype: str

In [46]:
df.iloc[0, :]

Name      Alice
Age          26
City         SF
Senior    False
Name: 0, dtype: object

In [47]:
df.iloc[:, 0]

0      Alice
1        Bob
2    Charlie
Name: Name, dtype: str

In [ ]:
# iloc uses index, loc uses names

## import data with pandas

In [50]:
df = pd.read_csv("students.csv")

FileNotFoundError: [Errno 2] No such file or directory: 'students.csv'